/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.spark.sql.execution.datasources.parquet.test.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroMapOfArray extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroMapOfArray\",\"namespace\":\"org.apache.spark.sql.execution.datasources.parquet.test.avro\",\"fields\":[{\"name\":\"string_to_ints_column\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"array\",\"items\":\"int\"},\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.Map<String,java.util.List<Integer>> string_to_ints_column;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public AvroMapOfArray() {}

  /**
   * All-args constructor.
   */
  public AvroMapOfArray(java.util.Map<String,java.util.List<Integer>> string_to_ints_column) {
    this.string_to_ints_column = string_to_ints_column;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public Object get(int field$) {
    switch (field$) {
    case 0: return string_to_ints_column;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: string_to_ints_column = (java.util.Map<String,java.util.List<Integer>>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'string_to_ints_column' field.
   */
  public java.util.Map<String,java.util.List<Integer>> getStringToIntsColumn() {
    return string_to_ints_column;
  }

  /**
   * Sets the value of the 'string_to_ints_column' field.
   * @param value the value to set.
   */
  public void setStringToIntsColumn(java.util.Map<String,java.util.List<Integer>> value) {
    this.string_to_ints_column = value;
  }

  /** Creates a new AvroMapOfArray RecordBuilder */
  public static Builder newBuilder() {
    return new Builder();
  }
  
  /** Creates a new AvroMapOfArray RecordBuilder by copying an existing Builder */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }
  
  /** Creates a new AvroMapOfArray RecordBuilder by copying an existing AvroMapOfArray instance */
  public static Builder newBuilder(AvroMapOfArray other) {
    return new Builder(other);
  }
  
  /**
   * RecordBuilder for AvroMapOfArray instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroMapOfArray>
    implements org.apache.avro.data.RecordBuilder<AvroMapOfArray> {

    private java.util.Map<String,java.util.List<Integer>> string_to_ints_column;

    /** Creates a new Builder */
    private Builder() {
      super(AvroMapOfArray.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.string_to_ints_column)) {
        this.string_to_ints_column = data().deepCopy(fields()[0].schema(), other.string_to_ints_column);
        fieldSetFlags()[0] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AvroMapOfArray instance */
    private Builder(AvroMapOfArray other) {
            super(AvroMapOfArray.SCHEMA$);
      if (isValidValue(fields()[0], other.string_to_ints_column)) {
        this.string_to_ints_column = data().deepCopy(fields()[0].schema(), other.string_to_ints_column);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'string_to_ints_column' field */
    public java.util.Map<String,java.util.List<Integer>> getStringToIntsColumn() {
      return string_to_ints_column;
    }
    
    /** Sets the value of the 'string_to_ints_column' field */
    public Builder setStringToIntsColumn(java.util.Map<String,java.util.List<Integer>> value) {
      validate(fields()[0], value);
      this.string_to_ints_column = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'string_to_ints_column' field has been set */
    public boolean hasStringToIntsColumn() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'string_to_ints_column' field */
    public Builder clearStringToIntsColumn() {
      string_to_ints_column = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings(value="unchecked")
    public AvroMapOfArray build() {
      try {
        AvroMapOfArray record = new AvroMapOfArray();
        record.string_to_ints_column = fieldSetFlags()[0] ? this.string_to_ints_column : (java.util.Map<String,java.util.List<Integer>>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
