/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.spark.sql.execution.datasources.parquet.test.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroNonNullableArrays extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroNonNullableArrays\",\"namespace\":\"org.apache.spark.sql.execution.datasources.parquet.test.avro\",\"fields\":[{\"name\":\"strings_column\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"maybe_ints_column\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"int\"}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<String> strings_column;
  @Deprecated public java.util.List<Integer> maybe_ints_column;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public AvroNonNullableArrays() {}

  /**
   * All-args constructor.
   */
  public AvroNonNullableArrays(java.util.List<String> strings_column, java.util.List<Integer> maybe_ints_column) {
    this.strings_column = strings_column;
    this.maybe_ints_column = maybe_ints_column;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public Object get(int field$) {
    switch (field$) {
    case 0: return strings_column;
    case 1: return maybe_ints_column;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: strings_column = (java.util.List<String>)value$; break;
    case 1: maybe_ints_column = (java.util.List<Integer>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'strings_column' field.
   */
  public java.util.List<String> getStringsColumn() {
    return strings_column;
  }

  /**
   * Sets the value of the 'strings_column' field.
   * @param value the value to set.
   */
  public void setStringsColumn(java.util.List<String> value) {
    this.strings_column = value;
  }

  /**
   * Gets the value of the 'maybe_ints_column' field.
   */
  public java.util.List<Integer> getMaybeIntsColumn() {
    return maybe_ints_column;
  }

  /**
   * Sets the value of the 'maybe_ints_column' field.
   * @param value the value to set.
   */
  public void setMaybeIntsColumn(java.util.List<Integer> value) {
    this.maybe_ints_column = value;
  }

  /** Creates a new AvroNonNullableArrays RecordBuilder */
  public static Builder newBuilder() {
    return new Builder();
  }
  
  /** Creates a new AvroNonNullableArrays RecordBuilder by copying an existing Builder */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }
  
  /** Creates a new AvroNonNullableArrays RecordBuilder by copying an existing AvroNonNullableArrays instance */
  public static Builder newBuilder(AvroNonNullableArrays other) {
    return new Builder(other);
  }
  
  /**
   * RecordBuilder for AvroNonNullableArrays instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroNonNullableArrays>
    implements org.apache.avro.data.RecordBuilder<AvroNonNullableArrays> {

    private java.util.List<String> strings_column;
    private java.util.List<Integer> maybe_ints_column;

    /** Creates a new Builder */
    private Builder() {
      super(AvroNonNullableArrays.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.strings_column)) {
        this.strings_column = data().deepCopy(fields()[0].schema(), other.strings_column);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.maybe_ints_column)) {
        this.maybe_ints_column = data().deepCopy(fields()[1].schema(), other.maybe_ints_column);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing AvroNonNullableArrays instance */
    private Builder(AvroNonNullableArrays other) {
            super(AvroNonNullableArrays.SCHEMA$);
      if (isValidValue(fields()[0], other.strings_column)) {
        this.strings_column = data().deepCopy(fields()[0].schema(), other.strings_column);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.maybe_ints_column)) {
        this.maybe_ints_column = data().deepCopy(fields()[1].schema(), other.maybe_ints_column);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'strings_column' field */
    public java.util.List<String> getStringsColumn() {
      return strings_column;
    }
    
    /** Sets the value of the 'strings_column' field */
    public Builder setStringsColumn(java.util.List<String> value) {
      validate(fields()[0], value);
      this.strings_column = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'strings_column' field has been set */
    public boolean hasStringsColumn() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'strings_column' field */
    public Builder clearStringsColumn() {
      strings_column = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'maybe_ints_column' field */
    public java.util.List<Integer> getMaybeIntsColumn() {
      return maybe_ints_column;
    }
    
    /** Sets the value of the 'maybe_ints_column' field */
    public Builder setMaybeIntsColumn(java.util.List<Integer> value) {
      validate(fields()[1], value);
      this.maybe_ints_column = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'maybe_ints_column' field has been set */
    public boolean hasMaybeIntsColumn() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'maybe_ints_column' field */
    public Builder clearMaybeIntsColumn() {
      maybe_ints_column = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings(value="unchecked")
    public AvroNonNullableArrays build() {
      try {
        AvroNonNullableArrays record = new AvroNonNullableArrays();
        record.strings_column = fieldSetFlags()[0] ? this.strings_column : (java.util.List<String>) defaultValue(fields()[0]);
        record.maybe_ints_column = fieldSetFlags()[1] ? this.maybe_ints_column : (java.util.List<Integer>) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
